<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tic Tac Toe Game</title>
  <link rel="stylesheet" href="/css/game.css">
</head>
<body>

<div id="game-container">
  <div class="row">User: <span id="user-symbol"></span></div>
  <div class="row">Modification: <span id="board-modification"></span></div>

  <div id="board"></div>
</div>

<script type="text/javascript" src="/js/game.js"></script>

</body>
</html>
